version: '3.4'

services:
  app:
    build: . 
    depends_on:
      - db
    environment:
      - host=5678


  db:
    image: postgres
    environment:
      - user=hada
      - pass=123

    volumes:
      -pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  